Repository UMC-ShowHoo/ShowHoo-Server, pull requests merged in 2024-08, with the labels that each got.

#47 [FEAT] 후기 작성 API 구현
  src/main/java/umc/ShowHoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/ShowHoo/web/performer/entity/Performer.java
  src/main/java/umc/ShowHoo/web/space/entity/Space.java
  src/main/java/umc/ShowHoo/web/spaceApply/repository/SpaceApplyRepository.java
  src/main/java/umc/ShowHoo/web/spaceReview/controller/SpaceReviewController.java
  src/main/java/umc/ShowHoo/web/spaceReview/converter/SpaceReviewConverter.java
  src/main/java/umc/ShowHoo/web/spaceReview/dto/SpaceReviewRequestDTO.java
  src/main/java/umc/ShowHoo/web/spaceReview/dto/SpaceReviewResponseDTO.java
  src/main/java/umc/ShowHoo/web/spaceReview/entity/SpaceReview.java
  src/main/java/umc/ShowHoo/web/spaceReview/entity/SpaceReviewImage.java
  src/main/java/umc/ShowHoo/web/spaceReview/exception/handler/SpaceReviewHandler.java
  src/main/java/umc/ShowHoo/web/spaceReview/repository/SpaceReviewRepository.java
  src/main/java/umc/ShowHoo/web/spaceReview/service/SpaceReviewService.java
  src/main/java/umc/ShowHoo/web/spaceReviewAnswer/controller/SpaceReviewAnswerController.java
  src/main/java/umc/ShowHoo/web/spaceReviewAnswer/dto/SpaceReviewAnswerRequestDTO.java
  src/main/java/umc/ShowHoo/web/spaceReviewAnswer/entity/SpaceReviewAnswer.java
  src/main/java/umc/ShowHoo/web/spaceReviewAnswer/repository/SpaceReviewAnswerRepository.java
  src/main/java/umc/ShowHoo/web/spaceReviewAnswer/service/SpaceReviewAnswerService.java
Labels: ✨feature

#52 [MODIFY] 공연자 프로필 수정
  src/main/java/umc/ShowHoo/web/performerProfile/controller/PerformerProfileController.java
  src/main/java/umc/ShowHoo/web/performerProfile/converter/PerformerProfileConverter.java
  src/main/java/umc/ShowHoo/web/performerProfile/dto/PerformerProfileRequestDTO.java
  src/main/java/umc/ShowHoo/web/performerProfile/entity/PerformerProfile.java
  src/main/java/umc/ShowHoo/web/performerProfile/service/PerformerProfileService.java
Labels: :recycle: refactor

#54 [FEAT] 공연자/공연장 - 대관 양식, 대관 서류 업로드/다운로드 API 구현 (#34)
  src/main/java/umc/ShowHoo/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/ShowHoo/web/Shows/dto/ShowsRequestDTO.java
  src/main/java/umc/ShowHoo/web/Shows/entity/Shows.java
  src/main/java/umc/ShowHoo/web/book/service/BookCommandServiceImpl.java
  src/main/java/umc/ShowHoo/web/rentalFile/controller/RentalFileController.java
  src/main/java/umc/ShowHoo/web/rentalFile/converter/RentalFileConverter.java
  src/main/java/umc/ShowHoo/web/rentalFile/dto/RentalFileRequestDTO.java
  src/main/java/umc/ShowHoo/web/rentalFile/dto/RentalFileResponseDTO.java
  src/main/java/umc/ShowHoo/web/rentalFile/entity/RentalFile.java
  src/main/java/umc/ShowHoo/web/rentalFile/handler/RentalFileHandler.java
  src/main/java/umc/ShowHoo/web/rentalFile/repository/RentalFileRepository.java
  src/main/java/umc/ShowHoo/web/rentalFile/service/RentalFileService.java
  src/main/java/umc/ShowHoo/web/space/entity/Space.java
Labels: ✨feature

#57 [FEAT] 공연장 등록, 공연장 세부정보 조회, 대관신청 추가 구현
  src/main/java/umc/ShowHoo/web/holiday/entity/Holiday.java
  src/main/java/umc/ShowHoo/web/holiday/repository/HolidayRepository.java
  src/main/java/umc/ShowHoo/web/peakSeasonRentalFee/dto/PeakSeasonRentalFeeRequestDTO.java
  src/main/java/umc/ShowHoo/web/peakSeasonRentalFee/entity/PeakSeasonRentalFee.java
  src/main/java/umc/ShowHoo/web/peakSeasonRentalFee/repository/PeakSeasonRentalFeeRepository.java
  src/main/java/umc/ShowHoo/web/rentalFee/repository/RentalFeeRepository.java
  src/main/java/umc/ShowHoo/web/rentalFee/service/RentalFeeService.java
  src/main/java/umc/ShowHoo/web/space/controller/SpaceController.java
  src/main/java/umc/ShowHoo/web/space/converter/SpaceConverter.java
  src/main/java/umc/ShowHoo/web/space/dto/SpaceRequestDTO.java
  src/main/java/umc/ShowHoo/web/space/dto/SpaceResponseDTO.java
  src/main/java/umc/ShowHoo/web/space/entity/Space.java
  src/main/java/umc/ShowHoo/web/space/service/SpaceService.java
  src/main/java/umc/ShowHoo/web/spaceApply/controller/SpaceApplyController.java
  src/main/java/umc/ShowHoo/web/spacePhoto/controller/SpacePhotoController.java
  src/main/java/umc/ShowHoo/web/spacePhoto/dto/SpacePhotoResponseDTO.java
  src/main/java/umc/ShowHoo/web/spacePhoto/service/SpacePhotoService.java
Labels: ✨feature, :recycle: refactor

#64 [MODIFY] 리뷰, 공연자 프로필 사진 관련 api 추가, 수정
  src/main/java/umc/ShowHoo/web/performerProfile/controller/PerformerProfileController.java
  src/main/java/umc/ShowHoo/web/performerProfile/converter/PerformerProfileConverter.java
  src/main/java/umc/ShowHoo/web/performerProfile/dto/PerformerProfileRequestDTO.java
  src/main/java/umc/ShowHoo/web/performerProfile/service/PerformerProfileService.java
  src/main/java/umc/ShowHoo/web/spaceReview/controller/SpaceReviewController.java
  src/main/java/umc/ShowHoo/web/spaceReview/dto/SpaceReviewRequestDTO.java
  src/main/java/umc/ShowHoo/web/spaceReview/repository/SpaceReviewImageRepository.java
  src/main/java/umc/ShowHoo/web/spaceReview/service/SpaceReviewService.java
Labels: ✨feature, :recycle: refactor

#63 [FEAT] 공연자 - 공연 준비: 예매자 관리 API 구현 (#56)
  src/main/java/umc/ShowHoo/web/Shows/controller/ShowsController.java
  src/main/java/umc/ShowHoo/web/book/controller/BookAdminController.java
  src/main/java/umc/ShowHoo/web/book/converter/BookConverter.java
  src/main/java/umc/ShowHoo/web/book/dto/BookResponseDTO.java
  src/main/java/umc/ShowHoo/web/book/entity/Book.java
  src/main/java/umc/ShowHoo/web/book/repository/BookRepository.java
  src/main/java/umc/ShowHoo/web/book/service/BookAdminService.java
  src/main/java/umc/ShowHoo/web/book/service/BookCommandServiceImpl.java
  src/main/java/umc/ShowHoo/web/cancelBook/entity/CancelBook.java
  src/main/java/umc/ShowHoo/web/cancelBook/repository/CancelBookRepository.java
  src/main/resources/application-prod.yml
Labels: ✨feature

#74 [FEAT] 공연자, 공연장 마이페이지 조회
  src/main/java/umc/ShowHoo/web/performer/repository/PerformerRepository.java
  src/main/java/umc/ShowHoo/web/performerProfile/controller/PerformerProfileController.java
  src/main/java/umc/ShowHoo/web/performerProfile/dto/PerformerProfileResponseDTO.java
  src/main/java/umc/ShowHoo/web/performerProfile/entity/PerformerProfile.java
  src/main/java/umc/ShowHoo/web/performerProfile/repository/PerformerProfileRepository.java
  src/main/java/umc/ShowHoo/web/performerProfile/service/PerformerProfileService.java
  src/main/java/umc/ShowHoo/web/space/controller/SpaceController.java
  src/main/java/umc/ShowHoo/web/space/converter/SpaceConverter.java
  src/main/java/umc/ShowHoo/web/space/service/SpaceService.java
  src/main/java/umc/ShowHoo/web/spacePrefer/repository/SpacePreferRepository.java
  src/main/java/umc/ShowHoo/web/spaceUser/controller/SpaceUserController.java
  src/main/java/umc/ShowHoo/web/spaceUser/dto/SpaceUserResponseDTO.java
  src/main/java/umc/ShowHoo/web/spaceUser/service/SpaceUserService.java
Labels: ✨feature

#80 [REFACTOR] 공연장 전체 조회 API grade값 수정
  src/main/java/umc/ShowHoo/web/space/converter/SpaceConverter.java
  src/main/java/umc/ShowHoo/web/space/entity/Space.java
  src/main/java/umc/ShowHoo/web/space/service/SpaceService.java
  src/main/java/umc/ShowHoo/web/spaceReview/service/SpaceReviewService.java
Labels: :recycle: refactor

#86 [FEAT] 공연자 알림 구현 #81
  src/main/java/umc/ShowHoo/web/audience/controller/AudienceController.java
  src/main/java/umc/ShowHoo/web/audience/converter/AudienceConverter.java
  src/main/java/umc/ShowHoo/web/audience/service/AudienceQueryService.java
  src/main/java/umc/ShowHoo/web/audience/service/AudienceQueryServiceImpl.java
  src/main/java/umc/ShowHoo/web/book/converter/BookConverter.java
  src/main/java/umc/ShowHoo/web/book/entity/Book.java
  src/main/java/umc/ShowHoo/web/book/repository/BookRepository.java
  src/main/java/umc/ShowHoo/web/book/service/BookAdminService.java
  src/main/java/umc/ShowHoo/web/book/service/BookCommandServiceImpl.java
  src/main/java/umc/ShowHoo/web/book/service/BookStatusUpdater.java
  src/main/java/umc/ShowHoo/web/book/validation/CheckSoldoutValidator.java
  src/main/java/umc/ShowHoo/web/notification/service/NotificationService.java
  src/main/java/umc/ShowHoo/web/performerProfile/entity/PerformerProfile.java
  src/main/java/umc/ShowHoo/web/rentalFile/controller/RentalFileController.java
  src/main/java/umc/ShowHoo/web/rentalFile/entity/RentalFile.java
  src/main/java/umc/ShowHoo/web/rentalFile/service/RentalFileService.java
  src/main/java/umc/ShowHoo/web/shows/controller/ShowsController.java
  src/main/java/umc/ShowHoo/web/shows/converter/ShowsConverter.java
  src/main/java/umc/ShowHoo/web/shows/dto/ShowsRequestDTO.java
  src/main/java/umc/ShowHoo/web/shows/dto/ShowsResponseDTO.java
  src/main/java/umc/ShowHoo/web/shows/entity/Shows.java
  src/main/java/umc/ShowHoo/web/shows/handler/ShowsHandler.java
  src/main/java/umc/ShowHoo/web/shows/repository/ShowsRepository.java
  src/main/java/umc/ShowHoo/web/shows/service/ShowsService.java
  src/main/java/umc/ShowHoo/web/showsDescription/converter/ShowsDscConverter.java
  src/main/java/umc/ShowHoo/web/showsDescription/entity/ShowsDescription.java
  src/main/java/umc/ShowHoo/web/showsPrefer/converter/ShowsPreferConverter.java
  src/main/java/umc/ShowHoo/web/showsPrefer/entity/ShowsPrefer.java
  src/main/java/umc/ShowHoo/web/showsPrefer/repository/ShowsPreferRepository.java
  src/main/java/umc/ShowHoo/web/showsPrefer/service/ShowsPreferCommandServiceImpl.java
  src/main/java/umc/ShowHoo/web/spaceApply/controller/SpaceApplyController.java
  src/main/java/umc/ShowHoo/web/spaceApply/service/SpaceApplyService.java
Labels: ✨feature

#98 [REFACTOR] Space, SpacePrefer 엔티티 설정 수정 및 에러 핸들링 추가
  src/main/java/umc/ShowHoo/web/space/controller/SpaceController.java
  src/main/java/umc/ShowHoo/web/space/dto/SpaceRequestDTO.java
  src/main/java/umc/ShowHoo/web/space/entity/Space.java
  src/main/java/umc/ShowHoo/web/space/repository/SpaceRepository.java
  src/main/java/umc/ShowHoo/web/space/service/SpaceService.java
  src/main/java/umc/ShowHoo/web/spacePrefer/service/SpacePreferService.java
Labels: :recycle: refactor

#103 [MODIFY] 공연자 공연준비 : 포스터 s3 저장 (#101)
  src/main/java/umc/ShowHoo/aws/s3/AmazonS3Manager.java
  src/main/java/umc/ShowHoo/web/rentalFile/controller/RentalFileController.java
  src/main/java/umc/ShowHoo/web/rentalFile/repository/RentalFileRepository.java
  src/main/java/umc/ShowHoo/web/rentalFile/service/RentalFileService.java
  src/main/java/umc/ShowHoo/web/shows/controller/ShowsController.java
  src/main/java/umc/ShowHoo/web/shows/service/S3Service.java
Labels: :recycle: refactor

#112 [FEAT] 공연자의 공연장 찜 유무 조회 #111
  src/main/java/umc/ShowHoo/web/space/controller/SpaceController.java
  src/main/java/umc/ShowHoo/web/spacePrefer/controller/SpacePreferController.java
  src/main/java/umc/ShowHoo/web/spacePrefer/repository/SpacePreferRepository.java
  src/main/java/umc/ShowHoo/web/spacePrefer/service/SpacePreferService.java
Labels: ✨feature

#119 [FEAT] 공연자 공연준비 - 포스터url 반환 API (#118)
  src/main/java/umc/ShowHoo/web/shows/controller/ShowsController.java
  src/main/java/umc/ShowHoo/web/shows/dto/ShowsRequestDTO.java
  src/main/java/umc/ShowHoo/web/shows/dto/ShowsResponseDTO.java
  src/main/java/umc/ShowHoo/web/shows/service/ShowsService.java
Labels: ✨feature
